HM-16: input and button components refactor with BaseComponent
frontend-park-mail-ru/2023_2_Hamster pull request #10
Opened 2023-10-01 20:22 UTC by 1qwaka

2023-10-01 20:35 UTC, Gallaann requested changes
Еще немного поправить, а так супер, очень помог)

2023-10-01 20:35 UTC, Gallaann commented on src/components/atoms/button/button.js
> +        }
Верни в пераметры конструктора `clickHandler = this.#clickHandler`
а `this.#state = {...this.#state, ...state};` в тело функции
`if (clickHandler) {
            this.#clickHandler = clickHandler;
        }` я бы написал как `if (clickHandler === 'function') {
            this.#clickHandler = clickHandler;
        }`

2023-10-01 20:35 UTC, Gallaann commented on src/components/atoms/button/button.js
> -    constructor(parent, state = this.#state, clickHandler = this.#clickHandler) {
`state = DEFAULT_BUTTON`

2023-10-01 20:35 UTC, Gallaann commented on src/components/atoms/input/input.js
> +        }
Аналогично с button

2023-10-01 22:21 UTC, Gallaann approved these changes

2023-10-02 11:49 UTC, F4lkr4m requested changes

2023-10-02 11:49 UTC, F4lkr4m commented on src/components/atoms/button/button.js
> +        const buttonElement = this.parent.querySelector('button');
Тут нужна проверка на парента, если его нет - то было бы удобно логнуть ошибку в консоль, чтобы было проще дебажить

2023-10-02 11:49 UTC, F4lkr4m commented on src/components/atoms/input/input.js
> +        //const inputElement = this.#parent.querySelector('input');
Если не нужна функция - то  удалить, если нужна то можно повесить на input   addEventListener('change', callback)

2023-10-02 11:49 UTC, F4lkr4m commented on src/pages/login/login.js
>          console.log(this.#isLogin)
Лишний лог

2023-10-02 17:59 UTC, F4lkr4m approved these changes
lgtm

2023-10-02 22:19 UTC, merged