HM-23: Add webpack
frontend-park-mail-ru/2023_2_Hamster pull request #22
Opened 2023-10-17 22:00 UTC by Gallaann

* Configure webpack
* Convert css to scss

2023-10-18 16:31 UTC, F4lkr4m commented on src/components/molecules/sidebar/sidebar.js
>  import { Button } from '../../atoms/button/button.js';
В вебпаке можно настроить алиасы, чтобы не страдать ../../../../../../../../../..

2023-10-18 16:37 UTC, F4lkr4m requested changes

2023-10-18 16:37 UTC, F4lkr4m commented on src/index.scss
>  @import "styles/fonts.css";
css? Вроде же теперь scss

2023-10-18 16:37 UTC, F4lkr4m commented on src/pages/layout/layout.js
> +            const balance = await getBalance(id);
А го оптимизируем - Promise.all

2023-10-18 16:37 UTC, F4lkr4m commented on src/pages/layout/layout.js
> +                    cardBalance: {
Давай все этот дефолтный стейт унесем куда-то в идеале создать рядом файлик - constants, потому что слишком много места занимает, а толку 0

2023-10-18 16:37 UTC, F4lkr4m commented on webpack.config.js
> +    // performance: {
Комменты убрать

2023-10-18 16:37 UTC, F4lkr4m commented on webpack.config.js
> +        extensions: ['.js', '.json'],
json зачем?

2023-10-18 16:54 UTC, Gallaann commented on src/index.scss
>  @import "styles/fonts.css";
Пока что и то, и другое

2023-10-18 16:55 UTC, Gallaann commented on src/components/atoms/input/input.scss
> +  width: auto;
Пока траблы ловлю, поэтому так, но это супер вариант

2023-10-18 18:31 UTC, F4lkr4m commented on src/index.scss
>  @import "styles/fonts.css";
Можно как минимум переименовать, чтобы не тащить и то и другое

2023-10-22 14:03 UTC, F4lkr4m approved these changes
Можно также создавать файлы бочки в корнях директорий index.js, которые в начале пытались делать

2023-10-22 22:00 UTC, merged