Dev/hm 3
frontend-park-mail-ru/2023_2_Hamster pull request #3
Opened 2023-09-27 14:09 UTC by CodeMaster482

2023-09-27 16:36 UTC, F4lkr4m requested changes

2023-09-27 16:36 UTC, F4lkr4m commented on src/atoms/input/input.hbs
> +    {{#if labelClass}}<label for="{{id}}" class="{{labelClass}}">{{labelText}}</label> {{/if}}
Это выглядит не очень красиво, давай сделаем красиво - 
![image](https://github.com/frontend-park-mail-ru/2023_2_Hamster/assets/31344471/81b22a39-22e4-447a-b050-d9f7df57ad7b)
Аналогично лучше с остальной версткой сделать

2023-09-27 16:36 UTC, F4lkr4m commented on src/atoms/input/input.html
Не совсем понимаю зачем этот файл в коммите, если использовал как ориентир для верстания, то лучше удалить из репозитория, чтобы мусор не копился

2023-09-27 16:36 UTC, F4lkr4m commented on src/atoms/input/input.js
> +    setState(newState) {
Кажется я где-то уже это видел, может уже стоит придумать какой-то общий класс?)

2023-09-27 16:36 UTC, F4lkr4m commented on src/atoms/input/input.hbs
> +    <input type="{{typeOfInput}}" {{#if autocompleteOff}} autocomplete="off" {{/if}} name="{{nameOfField}}" placeholder="{{placeholder}}" class="{{classInp}} js__{{nameOfField}}" {{#if id}} id="{{id}
Круто, что ты сделал input максимально гибким, он как вода - в какую емкость не засунь - прекрасно будет себя чуйствовать))) Но, в базовой комплектации (когда ты не прокидываешь пропсы(свойства)) он не должен быть голым 
![image](https://github.com/frontend-park-mail-ru/2023_2_Hamster/assets/31344471/1fd8b44c-039d-4952-84a1-3abedc4104c7)
Он изначально должен быть уже стилизован, ты не должен в него постоянно прокидывать классы. Ты лишь создаешь его управление по типу ввода текста, типа поля, плейсхолдера и прочего

2023-09-27 16:36 UTC, F4lkr4m commented on src/atoms/input/input.css
> +.input {
Вместо класса `.input` мы стилизуем просто `input` (как кнопку)

2023-09-27 16:36 UTC, F4lkr4m commented on src/atoms/input/input.css
> +    color: #858689;
Тут уникальный цвет какой-то или можно его использовать из токенов в теме?

2023-09-27 16:36 UTC, F4lkr4m commented on src/atoms/input/input.hbs
> +    {{#if labelClass}}<label for="{{id}}" class="{{labelClass}}">{{labelText}}</label> {{/if}}
Лейбл тоже можно стилизовать как input только указать область с помощью внешнего div - css:  .divBeforeInput label { //...css } - это чтобы лишние классы не пробрасывать, но в целом можно и классом оставить

2023-09-27 16:36 UTC, F4lkr4m commented on src/atoms/input/input.css
> +    color: #858689;
В общем лучше все цвета выносить в переменные, чтобы можно было удобно менять и переиспользовать, ты вроде там задавал как раз переменные

2023-09-27 16:36 UTC, F4lkr4m commented on src/atoms/input/Search.svg:Zone.Identifier
Это что?

2023-09-27 16:36 UTC, F4lkr4m commented on src/atoms/input/Search.svg
Все иконки, картинки - лучше складывать в отдельное место - например: assets/icons

2023-09-27 16:36 UTC, F4lkr4m commented on src/atoms/input/input.css
> +    font-family: Rubik, sans-serif;
Не заметил у Вовы этот момент - font-family должен задаваться на весь документ на самом верху - то есть для body

2023-09-27 16:36 UTC, F4lkr4m commented on src/styles/dark_theme/theme.css
> +    --focus-color: #687BB3;
focus-color для чего? Он еще где-то будет кроме input? Если не будет, то лучше его как минимум перенести поближе к объявлению переменных для input  на 41ую строчку

2023-09-27 17:09 UTC, Gallaann requested changes
Опять я прошляпил что-то, но разгребать придется)

2023-09-27 17:09 UTC, Gallaann commented on src/atoms/input/input.css
> +    color: #858689;
Кажется какой-то абсолютно рандомный цвет. Обновил цвета в фигме, посмотри, мб нужый тебе добавился

2023-09-27 17:09 UTC, Gallaann commented on src/atoms/input/input.css
> +    font-family: 'Poppins';
Noooooooo
Я это недоглядел, у нас только 2 шрифта Inter и Rubik

2023-09-27 17:09 UTC, Gallaann commented on src/styles/dark_theme/theme.css
> +    --input-text-primary-error-color: var(--error-color);
input только в одном цвете, нет смысла добавлять primary к названию файла

2023-09-27 17:09 UTC, Gallaann commented on src/styles/dark_theme/theme.css
> +    --diabled-color: #909090;
Опять новый цвет

2023-09-27 17:09 UTC, Gallaann commented on src/atoms/input/input.js
> +}
🤓

2023-09-28 18:41 UTC, F4lkr4m requested changes

2023-09-28 18:41 UTC, F4lkr4m commented on src/atoms/input/input.hbs
> +    <input type="{{typeOfInput}}" {{#if autocompleteOff}} autocomplete="off" {{/if}} name="{{nameOfField}}" placeholder="{{this.inputPlaceholder}}" class="input input__text {{#if this.inputImageLeft}
Так, в одну строчку не пишем все, должно быть читаемо. Обычно в линтерах 180/120 символов в строке, давай сделаем красиво - 
![image](https://github.com/frontend-park-mail-ru/2023_2_Hamster/assets/31344471/36e61f30-bc33-436a-a94b-06b49a00b7c0)
Как то примерно так

2023-09-28 18:41 UTC, F4lkr4m commented on src/atoms/input/input.hbs
> +    {{#if this.inputImageRight || this.inputImageLeft}}
На этой строчке компиляция hbs падает

2023-09-28 18:41 UTC, F4lkr4m commented on src/atoms/input/input.css
> +
Лишние пустые строчки в конце файла

2023-09-28 18:41 UTC, F4lkr4m commented on src/atoms/input/input.css
> +    font-family: 'Poppins';
Все еще мильён шрифтов

2023-09-28 18:41 UTC, F4lkr4m commented on src/atoms/input/input.css
> +.kg {
И что такое кг кстати?

2023-09-28 18:41 UTC, F4lkr4m commented on src/atoms/input/input.js
> +     * The state of the input component.
Все еще JSDoc не у конструктора, а у переменной

2023-09-28 20:59 UTC, Gallaann commented on src/index.html
> +
Что у вас здесь происходит

2023-09-29 11:30 UTC, Gallaann requested changes
Хорошо идешь, еще немного изменить

2023-09-29 11:30 UTC, Gallaann commented on package.json
>      "handlebars": "^4.7.8"
For what?

2023-09-29 11:30 UTC, Gallaann commented on src/atoms/input/input.css
> +.input {
Еще актуально

2023-09-29 11:30 UTC, Gallaann commented on src/atoms/input/input.css
> +    font-family: 'Poppins';
Актуально

2023-09-29 11:30 UTC, Gallaann commented on src/atoms/input/input.css
> +.kg {
Актуально

2023-09-29 11:30 UTC, Gallaann commented on src/atoms/input/input.css
> +
Актуально

2023-09-29 11:30 UTC, Gallaann commented on src/atoms/input/input.css
> +}
Может быть вторичный инпут? 
У кнопки модификаторы `primary` и `secondary` из-за того, что графически лучше разделять кнопку подтверждения от кнопки отмены. В инпуте я причины такое делать не вижу

2023-09-29 11:30 UTC, Gallaann commented on src/atoms/input/input.css
> +    color: var(--input-text-primary-error-color);
Ну это к тому же `кг`, назови его `units` лучше

2023-09-29 11:30 UTC, Gallaann commented on src/atoms/input/input.hbs
> +            {{/if}}"
Не хватает еще одного `if`, может быть инпут вообще без иконки, например, username

2023-09-29 11:30 UTC, Gallaann commented on src/assets/icons/Search.svg
👍

2023-09-29 11:30 UTC, Gallaann commented on src/styles/dark_theme/theme.css
> +    --inputs-minimal-width: 128px
👍

2023-09-29 11:30 UTC, Gallaann commented on src/styles/dark_theme/theme.css
> +    --input-text-primary-error-color: var(--error-color);
Должно быть закомменчено?

2023-09-29 11:30 UTC, Gallaann commented on src/atoms/input/input.js
> +     * The state of the input component.
Еще акутально

2023-09-29 21:45 UTC, F4lkr4m commented on src/atoms/input/input.css
> +}
Так это я так полагаю на задизейбленный стейт input'а - лучше разделять активный и задизейбленный стейт

2023-09-29 21:46 UTC, F4lkr4m requested changes
В целом поправить, что было раньше и что Вова спросил

2023-09-30 11:58 UTC, F4lkr4m commented
lgtm

2023-09-30 11:59 UTC, F4lkr4m approved these changes

2023-09-30 12:09 UTC, Gallaann approved these changes

2023-09-30 12:24 UTC, merged