HM-6: login and signup layout
frontend-park-mail-ru/2023_2_Hamster pull request #4
Opened 2023-09-27 14:11 UTC by DmitriyKomarovCoder

2023-09-27 16:01 UTC, Gallaann requested changes
Частично проблемы из-за меня, исправлю макет.

Забыл отметить, что боковая панель и картинка делятся не пополам, а в соотношении 40-60 где-то

2023-09-27 16:58 UTC, F4lkr4m requested changes
Также ветка неправильно названа не HW - а HM. Поменяй пожалуйста

2023-09-27 16:58 UTC, F4lkr4m commented on src/pages/login/image.svg
Все иконки, картинки в отдельную папочку, напр. assets/icons. Я уже писал Грише по этому поводу - вы там определитесь куда складывать будете

2023-09-27 16:58 UTC, F4lkr4m commented on src/pages/login/login.css
> +    flex: 2;
Зачем flex: 2?

2023-09-27 16:58 UTC, F4lkr4m commented on src/pages/login/mobilev.svg
Пхахахах

2023-09-27 16:58 UTC, F4lkr4m commented on src/pages/login/login.css
> +}
Да, мобилку делаем после РК2, пока не надо заморачиваться

2023-09-27 16:58 UTC, F4lkr4m commented on src/pages/login/login.css
> +.login-form input[type="text"],
Все инпуты будут внешними, как и кнопки. Их тут стилизовать не нужно

2023-09-27 16:58 UTC, F4lkr4m commented on src/styles/fonts.css
> +font-family: Inter;
Базовое семейство шрифтов должно определяться для body

2023-09-28 17:01 UTC, F4lkr4m requested changes

2023-09-28 17:01 UTC, F4lkr4m commented on src/pages/login/login.js
> +     * @constructor
И опиши там объект стейта по типу - https://gomakethings.com/how-to-document-object-properties-with-jsdoc/#documenting-object-properties-with-jsdoc

2023-09-28 17:05 UTC, F4lkr4m commented on src/pages/login/login.js
> +export class Login {
Это класс только на логин. Думаю было бы удобно сделать универсальный компонент. LoginOrSignUp - который на вход будет принимать аргумент по типу isLogin - и на основе этого менять верстку

2023-09-29 05:28 UTC, F4lkr4m requested changes
Уже близко к концу, остались мелкие поправки. А так хорош! Молодец!

2023-09-29 05:28 UTC, F4lkr4m commented on src/pages/login/login.js
> +    #IsLogin;
isLogin - с маленькой буквы нейминг

2023-09-29 05:28 UTC, F4lkr4m commented on src/pages/login/login.hbs
> +        <p class="font-caption"> Do you have account? </p> <a href="#">Login</a>
Отступы

2023-09-29 05:28 UTC, F4lkr4m commented on src/index.js
> +let Form = {}; // replace in real form
Не забываем про объявление через  let/const

2023-09-29 05:28 UTC, F4lkr4m commented on src/pages/login/login.js
> +            const fontContainer = this.#parent.querySelector('#form-container')
#form-container - это id, но в верстке такого id нет, но есть класс. Чтобы обратиться к классу надо написать через точку - .form-container

2023-09-29 05:28 UTC, F4lkr4m commented on src/pages/login/login.js
> +            this.#state.imageLogin = "../../images/peopleReg.svg"
Путь до дефолтной картинки вынеси в константу и помести ее над классом

2023-09-29 05:28 UTC, F4lkr4m commented on src/pages/login/login.hbs
>      <div class="login-form">
Тут класс по БЭМ нужен тоже

2023-09-29 21:29 UTC, Gallaann reviewed
Просто посмотрел, ждем Серёгу для детального ревью 🤠

2023-09-29 21:29 UTC, Gallaann commented on src/pages/login/login.hbs
> +            <p class="font-link"> Do you have account? </p> <a href="#">Login</a>
Надо будет в макете переделать на ссылочку, спасибо, так получше будет

2023-09-29 21:29 UTC, Gallaann commented on src/pages/login/login.css
> +    font-family: Arial, Helvetica, sans-serif;
Ого.......

2023-09-29 21:29 UTC, Gallaann commented on src/pages/login/login.css
> +}
Вот это круто

2023-09-29 21:29 UTC, Gallaann commented on src/pages/login/login.css
> +    top: 25%; /* Помещаем изображение на 50% высоты родительского элемента */
Сюда бы англичанский

2023-09-29 21:29 UTC, Gallaann commented on src/pages/login/login.css
> +}
+вайб

2023-09-29 21:29 UTC, Gallaann commented on src/styles/fonts.css
> +  font-family: Montserrat;
Может быть окей, может быть не. По факту шрифт только для страницы регистрации и логина, потому что мне не понравился внешний вид с другими, кажется

2023-09-29 21:39 UTC, F4lkr4m requested changes

2023-09-29 21:39 UTC, F4lkr4m commented on src/index.js
> +let Form = {}; // replace in real form
Здесь если что нужен const - т.к. переменная по коду не меняется.

2023-09-29 21:39 UTC, F4lkr4m commented on src/pages/login/login.css
> +    font-family: Arial, Helvetica, sans-serif;
Да, 43 шрифта не супер крутая тема, лучше обговорить с командой и определиться с каким шрифтом жить

2023-09-29 21:39 UTC, F4lkr4m commented on src/pages/login/login.css
> +    top: 25%; /* Помещаем изображение на 50% высоты родительского элемента */
Да, лучше придерживаться одно вида комментов

2023-09-29 21:39 UTC, F4lkr4m commented on src/pages/login/login.hbs
> +            <p class="font-link"> Do you have account? </p> <a href="#">Login</a>
Надо добавить прокидывание ссылки

2023-09-29 21:39 UTC, F4lkr4m commented on src/pages/login/login.hbs
> +
Вот тут нужен шаблон handlebars для прокидывания формы по типу {{> loginForm }}

2023-09-29 21:39 UTC, F4lkr4m commented on src/pages/login/login.hbs
> +
Но если не работает регистрация хелперов, то можно не делать до тех пор пока не заведете эту фичу

2023-09-29 21:39 UTC, F4lkr4m commented on src/pages/login/login.js
> +const imageURL = "../../images/peopleLoginReg.svg";
Все константы через SCREAMING_SNAKE_CASE

2023-09-29 21:39 UTC, F4lkr4m commented on src/pages/login/login.js
> +        this.#isLogin = (islogin) ? true : false;
Скобки на тернарнике не нужны

2023-09-29 21:41 UTC, F4lkr4m commented on src/pages/login/login.js
> +        Handlebars.registerPartial('button', '{{buttonHTML}}');
registerPartial не так работает по моим ощущениям) Лучше удалить эту строчку и сделать с помощь partials штуки в других фичах уже. Сейчас мучаться с этим не будем

2023-09-29 21:41 UTC, F4lkr4m commented on src/styles/fonts.css
> +  font-family: Montserrat;
Больше шрифтов богу шрифтов))0)

2023-09-29 21:58 UTC, DmitriyKomarovCoder commented on src/pages/login/login.css
> +    top: 25%; /* Помещаем изображение на 50% высоты родительского элемента */
Это на жпитишном, я уберу их

2023-09-29 23:09 UTC, Gallaann requested changes
Уже почти все

2023-09-29 23:09 UTC, Gallaann commented on src/pages/login/login.js
> +     * @param {Object} [state={}] - The initial state of the login form. (optional)
Надо перенести property state'а к конструктору

2023-09-30 10:19 UTC, F4lkr4m requested changes
Два мелких исправления поправить - потом соедини все коммиты в один и можно мерджить

2023-09-30 10:19 UTC, F4lkr4m commented on src/index.js
> +const IsLogin = false;
isLogin с маленькой буквы

2023-09-30 11:42 UTC, F4lkr4m commented
lgtm

2023-09-30 11:42 UTC, F4lkr4m approved these changes

2023-09-30 11:43 UTC, Gallaann approved these changes

2023-09-30 11:43 UTC, merged